### ISSUE TITLE
How to extend this?

### ISSUE THREAD

**Issue by alextaymx** [asagar60/Siamese-Neural-Networks-for-One-shot-Image-Recognition#1]
Hi there, I'm working on product image similarity checking. May I know how do I extend this work so that it works for Color images and output a similarity score of the 2 input images?

**Comment by asagar60** [comment]
Hey, since color images are 3-dimensional, you can re use existing model , by changing the input shape here, 
![image](https://user-images.githubusercontent.com/60076868/106380206-a5c16c00-63d6-11eb-8cb9-52ee66c3a456.png)

I have few ideas though :
 a. If model performs poorly ( which i suppose , it will ) , you can always add more layers and retrain on your dataset.
 b. You can use pre-trained model as base model (like vgg19 , resnet or densenet architectures) and get a feature vectors by removing last classification layer. and then build a model on top of that ,which will give the similarity scores.

**Comment by alextaymx** [comment]
I am able to extract feature vectors from VGG16, "build a model on top of that ,which will give the similarity scores", for this, do u mean replace the convnet with vgg, then remain some of the layers for siamese?

**Comment by asagar60** [comment]
You can do these , e.g
1.  Replace convnet features with VGG extracted features , (freeze them) , but add few dense layers in between, and train the model , here i have only used 1 dense layer at the end with 1 neuron.
2. Do same as above but retrain those feature vectors  along with the network, that way , similar products will have close feature vectors.

![image](https://user-images.githubusercontent.com/60076868/107019607-e26ed800-67c7-11eb-9694-feb5326a95bc.png)
